# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f591cd6900f675abf78021d492f24e3"
name = "checkout-order"
handle = "checkout-order-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "vijay-dev-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
